name: docker-exodus
on:
  push:
    branches: [ "master" ]

concurrency:  
  group: ${{ github.workflow}}-${{ github.head_ref }}  
  cancel-in-progress: true

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          context: docker/exodus
          push: true
          tags: mrbuche/exodus:latest
      - name: Delay before pull
        run: sleep 234s
  test-latest:
    needs: build-latest
    runs-on: ubuntu-latest
    container: mrbuche/exodus
    steps:
      - name: Docker pull and test
        run: |
          python -c 'import exodus3 as exodus'
